spring.application.name=career-pilot-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/career_pilot
spring.datasource.username=sorim

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true